fix KM_TYPE_NR undeclared in sched.h on 32 bit x86
Patch peter_zijlstra-re-_3_0-rt4.patch causes 32 bit compilations to fail with:
sched.h:1592:17: error: ‘KM_TYPE_NR’ undeclared here (not in a function)

Including asm/kmap_types in sched.h resolves the issue.

Signed-off-by: Darren Hart <dvhart@linux.intel.com>
CC: Peter Zijlstra <peterz@infradead.org>
CC: Bruce Ashfield <bruce.ashfield@windriver.com>